# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Living Atlases Community
email: ala-portal@lists.gbif.org
description: >- # this means to ignore newlines until "baseurl:"
  The open community around the Atlas of Living Australia platform.
  As GBIF nodes, one of our goals is to highlight our publishers and their data.
  To achieve this, the Atlas of Living Australia (ALA) developed a huge open
  source platform with several modules re-usable by other organizations.
  Since 2013, the community around this tool has organized technical workshops
  to present ALA modules to other institutions that wanted to implement it,
  to improve already existing national data portals and to learn from each other’s
  achievements.
# the base hostname & protocol for your site, e.g. http://example.com
#url: https://web-demo.l-a.site
baseurl:
twitter_username: livingatlases
github_username:  jekyll
repository: living-atlases/la-website
permalink: /:categories/:title/

# Build settings

plugins:
  - jekyll-email-protect
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - get-screenshots.sh
   - watch.sh
   - README.md
   - TOKEEP.txt
   - deploy.sh
#   - node_modules/
   - vendor
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - bundle/

collections: 
  events:
      output: true
      sort_by: year
  projects:
      output: true
      sort_by: year
  participants:
      output: true
      sort_by: institution 
sass:
  sass_dir: assets/css

include:
  - .well-known
